export default {
  'APP_DELIVERY_METHOD_UPDATE': 'APP_DELIVERY_METHOD_UPDATE',
  'APP_DELIVERY_ADDRESS_UPDATE': 'APP_DELIVERY_ADDRESS_UPDATE',
  'APP_PICKUP_UPDATE': 'APP_PICKUP_UPDATE',
  'APP_ORDER_CANCEL': 'APP_ORDER_CANCEL',
}